export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const SET_LOADING_TEXT = 'SET_LOADING_TEXT'
export const SET_TITLE = 'SET_TITLE'
export const SET_BACK = 'SET_BACK'
